### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by jma** [inveniosoftware/invenio-app#5]
Is it possible to add a description to explain how to create a new instance? Such as cloning this repo, change the name of this into that and so on? Or do you have plan to provide a template using `cookiecutter` for this?

Thanks.

**Comment by lnielsen** [comment]
👍 I guess the best would be to add a small ``exampleapp`` like in other modules? I think that would be the most descriptive. Afterwards there's a general chapter for Invenio on how to bootstrap your own instance instead of using one of the flavours like [invenio-app-ils](https://github.com/inveniosoftware/invenio-app-ils) (btw, right now ILS is an example app of this repo)

**Comment by lnielsen** [comment]
We will provide a cookiecutter-invenio-instance and improve the general Invenio documentation to use this.
